henninghall/react-native-date-picker

README.md, android/src/main/java/com/henninghall/date_picker/DatePickerManager.java, android/src/main/java/com/henninghall/date_picker/PickerView.java, android/src/main/java/com/henninghall/date_picker/wheelFunctions/AnimateToDate.java, android/src/main/java/com/henninghall/date_picker/wheelFunctions/Refresh.java, android/src/main/java/com/henninghall/date_picker/wheelFunctions/SetDate.java, android/src/main/java/com/henninghall/date_picker/wheelFunctions/WheelFunction.java, android/src/main/java/com/henninghall/date_picker/wheels/AmPmWheel.java, android/src/main/java/com/henninghall/date_picker/wheels/DayWheel.java, android/src/main/java/com/henninghall/date_picker/wheels/HourWheel.java, android/src/main/java/com/henninghall/date_picker/wheels/MinutesWheel.java, android/src/main/java/com/henninghall/date_picker/wheels/Wheel.java, example/App.js
Now possible to use the minuteInterval prop.
=> Minute interval support.

android/build.gradle
=> Android compile fix

android/src/main/java/com/henninghall/date_picker/WheelOrderUpdater.java
=> Bugfix: Crashes on date mode for some locales.

index.d.ts
=> Added typings

android/src/main/java/com/henninghall/date_picker/wheels/DayWheel.java
=> Fix DayWheel interval forming when either maximumDate or minimumDate prop is missing

android/src/main/java/com/henninghall/date_picker/wheels/DayWheel.java
Revise the date format that is used for Chinese
=> Handle Chinese date format

android/build.gradle
Fixes https://github.com/henninghall/react-native-date-picker/issues/89
=> Bumped NumberPickerView library version to fix initialization bug on hour wheel.

DatePickerAndroid.js, DatePickerIOS.js, propChecker.js
Display better errors when applying invalid props
=> Improve invalid prop errors

propTypes.js
Changing this from a series of binary or operations to an array closes #146
=> minuteInterval propType is an array

index.d.ts
Export DatePickerProps will help other developers easier to create implement components with extends Props
=> Export DatePickerProps

android/src/main/java/com/henninghall/date_picker/DayFormats.java
- Change long form to short form for week days
=> Change default date format for Finnish

ios/RNDatePicker/RNDatePickerManager.h
Fixes https://github.com/henninghall/react-native-date-picker/issues/214
=> remove duplicated meta method UIDatePickerMode

android/build.gradle, android/src/main/java/com/henninghall/date_picker/pickers/AndroidNative.java, android/src/main/java/com/henninghall/date_picker/pickers/IosClone.java, android/src/main/java/com/henninghall/date_picker/pickers/Picker.java, android/src/main/java/com/henninghall/date_picker/ui/WheelChangeListenerImpl.java, android/src/main/java/com/henninghall/date_picker/ui/Wheels.java
=> bugfix: fast scroll flickering

android/src/main/java/com/henninghall/date_picker/ui/Wheels.java, android/src/main/java/com/henninghall/date_picker/wheels/AmPmWheel.java, android/src/main/java/com/henninghall/date_picker/wheels/MinutesWheel.java, android/src/main/java/com/henninghall/date_picker/wheels/Wheel.java, android/src/main/res/layout/ios_clone.xml
Fixes https://github.com/henninghall/react-native-date-picker/issues/233
=> fix picker width and wheel spacing

android/src/main/java/com/henninghall/date_picker/DerivedData.java, android/src/main/java/com/henninghall/date_picker/wheels/MinutesWheel.java, android/src/main/java/com/henninghall/date_picker/wheels/Wheel.java, src/DatePickerAndroid.js
fixes https://github.com/henninghall/react-native-date-picker/issues/235
=> center 24h time mode wheels

android/src/main/java/com/henninghall/date_picker/pickers/AndroidNative.java
Fixes https://github.com/henninghall/react-native-date-picker/issues/238
=> bugfix: onDateChange not called on tap for androidNative variant

examples/detox/package.json, package.json, src/DatePickerAndroid.js, yarn.lock
Replaces moment.js with vanilla addMinutes as discussed in #173
=> Removed dependency to moment.js

android/src/main/java/com/henninghall/date_picker/ui/Wheels.java
Reported here: https://github.com/henninghall/react-native-date-picker/issues/21#issuecomment-708075204
=> fix android compilation issues below sdk 26

ios/RNDatePicker/RNDatePickerManager.m
Reported here: https://github.com/henninghall/react-native-date-picker/issues/244#issuecomment-708583240
=> fix iOS compilation issues

examples/detox/src/examples/Advanced.js, examples/detox/src/propPickers/FadeToColor.js, src/colorToHex.js
fixes https://github.com/henninghall/react-native-date-picker/issues/258
=> fix: fadeToColor "none" throws exception

android/src/main/java/com/henninghall/date_picker/Utils.java, android/src/main/java/com/henninghall/date_picker/ui/WheelChangeListenerImpl.java, android/src/main/java/com/henninghall/date_picker/ui/Wheels.java, android/src/main/java/com/henninghall/date_picker/wheels/DateWheel.java, android/src/main/java/com/henninghall/date_picker/wheels/Wheel.java, examples/detox/e2e/tests/invalidDates.spec.js
Fixes https://github.com/henninghall/react-native-date-picker/issues/277
=> Bugfix: Scroll away from invalid dates

android/src/main/res/values-he/strings.xml
Fully translated to Hebrew, also needs RTL support to work correctly.
=> Added Hebrew translation

ios/RNDatePicker/DatePicker.m
fixes https://github.com/henninghall/react-native-date-picker/issues/344
=> fix: only allow gregorian calendar

android/build.gradle, android/src/main/res/layout/ios_clone.xml, android/src/main/res/layout/native_picker.xml
fixes https://github.com/henninghall/react-native-date-picker/issues/339
=> feat: RTL support

android/src/main/java/com/henninghall/date_picker/pickers/AndroidNative.java, android/src/main/java/com/henninghall/date_picker/pickers/IosClone.java, android/src/main/java/com/henninghall/date_picker/pickers/Picker.java, android/src/main/java/com/henninghall/date_picker/wheelFunctions/TextColor.java, examples/detox/android/app/build.gradle, examples/detox/android/build.gradle, examples/detox/src/examples/Minimal.js
fixes https://github.com/henninghall/react-native-date-picker/issues/333
=> fix: native variant text color fix for Android 10 (sdk 29)

android/src/main/java/com/henninghall/date_picker/DatePickerModule.java, android/src/main/java/com/henninghall/date_picker/Emitter.java, src/DatePickerAndroid.js
fixes https://github.com/henninghall/react-native-date-picker/issues/394
=> fix: date changes for all mounted android modal pickers

src/DatePickerAndroid.js, src/DatePickerIOS.js
Fixes https://github.com/henninghall/react-native-date-picker/issues/415
Fixes issue solved by https://github.com/henninghall/react-native-date-picker/pull/452
=> Fix: Modal open multiple times 

package.json, yarn.lock
=> add prop-types dependecy

ios/RNDatePicker/RNDatePickerManager.m
Fixes https://github.com/henninghall/react-native-date-picker/issues/478
iPhone
iPad
=> fix iOS modal landscape design glitch

android/src/main/res/values-fr/strings.xml, android/src/main/res/values-nl/strings.xml
Added Dutch + French translation labels
=> Add NL + FR strings

android/src/main/java/com/henninghall/date_picker/DatePickerModule.java, ios/RNDatePicker/RNDatePickerManager.h, ios/RNDatePicker/RNDatePickerManager.m, src/DatePickerAndroid.js, src/DatePickerIOS.js
Solves https://github.com/henninghall/react-native-date-picker/issues/601
=> Closes modal date picker

android/src/main/java/com/henninghall/date_picker/DatePickerModuleImpl.java
Make local variable final to resolve compilation error when building react native app
=> make picker final

android/src/newarch/java/com/henninghall/date_picker/DatePickerModule.java, src/fabric/NativeRNDatePicker.ts
fixes https://github.com/henninghall/react-native-date-picker/issues/699
=> fix: listener error on android new arch

ios/DatePicker.m
=> fix: fix the build error on iOS

android/src/main/java/com/henninghall/date_picker/State.java, src/DatePickerAndroid.js
Fixes https://github.com/henninghall/react-native-date-picker/issues/763
=> fix: occasional setSeconds error on min/maxDate

android/src/main/java/com/henninghall/date_picker/DatePickerModuleImpl.java, android/src/main/java/com/henninghall/date_picker/PickerView.java
Regression, introduced in 5.0.2
=> fix: disable modal confirm while wheel spinning
