DatePickerAndroid.js
android/src/main/java/com/henninghall/date_picker/DatePickerManager.java
android/src/main/java/com/henninghall/date_picker/PickerView.java
android/src/main/java/com/henninghall/date_picker/Utils.java
android/src/main/java/com/henninghall/date_picker/wheelFunctions/AnimateToDate.java
android/src/main/java/com/henninghall/date_picker/wheelFunctions/SetDate.java
android/src/main/java/com/henninghall/date_picker/wheels/DayWheel.java
android/src/main/java/com/henninghall/date_picker/wheels/Wheel.java
android/src/main/java/com/henninghall/date_picker/wheels/YearWheel.java

This fix lets us avoid translating dates between timezones using `new Date().getTimezoneOffset()`. If we are lucky this might solve all problems with `timeZoneOffsetInMinutes`.
It will need some more testing before merging, but hopefully this should match the ios behaviour.

Fix for timezone bug in android picker

---

android/src/main/java/com/henninghall/date_picker/wheels/DayWheel.java

Fixed the format of dates when passing ja to rocaleprops.
| japanese_ios_picker |  |
| --- | --- |
| <img width="335" alt="スクリーンショット 2019-05-08 16 44 33" src="https://user-images.githubusercontent.com/34805701/57358736-021b3b80-71b1-11e9-93be-95899ced4f35.png"> |  |
| old_android_picker | fix_android_picker |
| ![スクリーンショット 2019-05-08 16 41 30](https://user-images.githubusercontent.com/34805701/57358606-c54f4480-71b0-11e9-9842-e23786b394eb.png) | ![スクリーンショット 2019-05-08 16 45 04](https://user-images.githubusercontent.com/34805701/57358691-f16ac580-71b0-11e9-90d3-b55ffedb6913.png) |

Add japanase day format 

---

android/src/main/java/com/henninghall/date_picker/wheels/DayWheel.java

I added Korean day format for DayWheel.
The following improvement is minor, but will help make it easier for Koreans to use this library.
If there is the same problem in future iOS environment, I will leave the improvement as PR.

Add Korean(ko) day format for DayWheel

---

DatePickerIOS.js
ios/RNDatePicker/DatePicker.m

Fixes https://github.com/henninghall/react-native-date-picker/issues/72

Keep "Today"-string when changing text color.

---

index.d.ts

Thanks very much for this library -- it's great!
I was getting an error using it with Typescript:
```
node_modules/react-native-date-picker/index.d.ts:87:1 - error TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.
class DatePicker extends Component<Props> {}
~~~~~
```
This PR addresses the problem (at least on my machine).

Fix Typescript compilation bug

---

DatePickerAndroid.js

Fixes #112.
Had a look into the code for `DatePickerIOS` as of the [latest commit](https://github.com/facebook/react-native/blob/c10c147bccd001dcff152fb5c8ea9fd7f590c868/Libraries/Components/DatePicker/DatePickerIOS.ios.js) to `react-native` and it doesn't seem that `DatePickerIOS.ios.js` even defined `propTypes` in the first place for `DatePickerAndroid.propTypes = DatePickerIOS.propTypes` to even use usefully.
It just comes out as setting `DatePickerAndroid.propTypes = undefined`.
So simple fix it seems is to simply remove that line and remove the import of `DatePickerIOS` from `react-native` in `DatePickerAndroid.js` for this package, as the [deprecation warning is raised by a getter for the exported component](https://github.com/facebook/react-native/blob/21f1cce148b64d9b261e9d95d18ba6 …

Suppress "DatePickerIOS has been merged..." warning

---

README.md
ios/RNDatePicker/DatePicker.m
propChecker.js

Displays today string even if dark mode on iOS 13. 
Replaces the "Today" string when a date when the text color is set to other than black or white since other colors are not supported on iOS 13. 
Fixes https://github.com/henninghall/react-native-date-picker/issues/113
Fixes https://github.com/henninghall/react-native-date-picker/issues/119

Bugfix: Text color on iOS 13 not displayed properly 

---

android/src/main/java/com/henninghall/date_picker/PickerView.java
android/src/main/java/com/henninghall/date_picker/WheelChangeListenerImpl.java
android/src/main/java/com/henninghall/date_picker/wheels/AmPmWheel.java
android/src/main/java/com/henninghall/date_picker/wheels/DateWheel.java
android/src/main/java/com/henninghall/date_picker/wheels/DayWheel.java
android/src/main/java/com/henninghall/date_picker/wheels/HourWheel.java
android/src/main/java/com/henninghall/date_picker/wheels/MinutesWheel.java
android/src/main/java/com/henninghall/date_picker/wheels/MonthWheel.java
android/src/main/java/com/henninghall/date_picker/wheels/Wheel.java
android/src/main/java/com/henninghall/date_picker/wheels/YearWheel.java
examples/advanced/package.json
examples/advanced/yarn.lock

Fixes an bug that was introduced in 2.7.0 by separating display format and value format properly.
Fixes https://github.com/henninghall/react-native-date-picker/issues/111

Bugfix: onDateChange not called for some locales

---

ios/RNDatePicker/DatePicker.m

Using this solution https://github.com/facebook/react-native/pull/23923/files#diff-3bdf2dca7c43eafcf85f91d9475bec58
Fixes: https://github.com/henninghall/react-native-date-picker/issues/132

Bugfix: iOS minute interval not working in time mode

---

android/src/main/java/com/henninghall/date_picker/DayFormats.java
android/src/main/java/com/henninghall/date_picker/LocaleUtils.java
android/src/main/java/com/henninghall/date_picker/props/LocaleProp.java

- Add missing Chinese locales. Fixes https://github.com/henninghall/react-native-date-picker/issues/170 
- Prevent crash related to parsing of default locales. Fixes https://github.com/henninghall/react-native-date-picker/issues/169

Fixing different language related crashes

---

.github/workflows/android.yml
android/src/main/java/com/henninghall/date_picker/LocaleUtils.java
android/src/main/java/com/henninghall/date_picker/Utils.java
examples/detox/e2e/tests/displayText.spec.js

When language is Chinese or Japanese in Android and mode is 'date', the method 'getDatePattern' return a string without space, so the picker show wrong data.

fix  bug when language is Chinese or Japanese in Android

---

android/src/main/java/com/henninghall/date_picker/LocaleUtils.java

The getPatternIncluding method would return quoted pieces if the contents of the quoted part included the format letter.
For instance for Danish (da_DK), the pattern is `"EEE 'den' d. MMM"`. If we are calling `getPatternIncluding("d", "da_DK")`, the method would return `"den'"`, but we would actually like to return `"d."`.
This commit ignores pieces with apostrophe (`'`) in them.
Fixes #194 
This might also handle #185, I'm not sure.
On a sidenote, I also think `getFullPatternPieces` is buggy (because of `getDatePattern`). I'd expect `getFullPatternPieces("da_DK")` to return this list: `["EEE", "'den'", "d.", "MMM"]`. Instead, it returns `["EEE", "'", "den'", "d.", "MMM"]`. It's the regex in `getDatePattern` that doesn't handle apostrophes (this line: `.replaceAll("([a-zA-Z]+)", " $1")`). …

Fix return of wrong pattern piece

---

android/src/main/java/com/henninghall/date_picker/LocaleUtils.java

By properly searching for the first undescore

Fix zh_* locale parsing

---

android/src/main/res/layout/native_picker.xml

fixes https://github.com/henninghall/react-native-date-picker/issues/210

adaptive am pm width

---

android/src/main/java/com/henninghall/date_picker/Formats.java

I seems like some locales were removed in this PR: https://github.com/henninghall/react-native-date-picker/pull/204 when DayFormats.java was replaced with Formats.java. This breaks the date picker for Norwegian Nynorsk (nn) on Android devices. Adding the locale in Formats.java fixes the issue for this particular locale.
Tested by editing directly in node_modules in our own app project.

Fix nynorsk (nn) locale by adding it to Formats

---

react-native-date-picker.podspec

Latest Xcode 12 fails to build while without a module to depend on React-Core directly hence this change is necessary for all native modules on iOS. For more details please check: facebook/react-native#29633
Use this branch to install with an app running on Xcode 12.
| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |

fix: Xcode 12 compatibility

---

.github/workflows/android-detox.yml
android/src/main/java/com/henninghall/date_picker/Utils.java
android/src/main/java/com/henninghall/date_picker/pickers/AndroidNative.java
android/src/main/java/com/henninghall/date_picker/ui/WheelChangeListenerImpl.java
examples/detox/android/app/build.gradle
examples/detox/android/app/src/test/java/ShortestScrollOption.java
src/propChecker.js

Fixes an issue occurring with setup: 
- android
- androidVariant: `nativeAndroid`
- scrolling below `minimumDate` or scrolling above `maximumDate`
This could cause the wheel to spin infinitely which lead to OutOfMemoryError
Fixes https://github.com/henninghall/react-native-date-picker/issues/264, https://github.com/henninghall/react-native-date-picker/issues/257

fix: android native variant min/max scrolling issues

---

android/src/main/java/com/henninghall/date_picker/wheels/AmPmWheel.java
android/src/main/java/com/henninghall/date_picker/wheels/HourWheel.java
examples/manual-tests/daylight-saving.md

Fixes these daylight saving related bugs:
- am/am is shown in am/pm wheel
- an hour value is missing in hour wheel and a duplicated hour is added
Fixes https://github.com/henninghall/react-native-date-picker/issues/262

fix: bugs occurring on daylight saving day

---

android/src/main/java/com/henninghall/date_picker/pickers/AndroidNative.java

**Fixes #295**
The application stops responding when the react native date picker component is unmounted and there are pending post delayed callbacks yet to run on the AndroidNative.java picker.
**What I did:**
I've added a handler instance in the class and replaced all the inline new Handler() found in the class plus I've overridden the onDetachedFromWindow method so when the component is unmounted we can cancel all the pending callbacks and avoid the problem.
I've tested the fix with a patch package applied to the example repo that I've created to reproduce the issue (mentioned in #295) and applied to my working project too. Both tested with the AVD and some physical samsung devices.

fix: android native variant stops responding at unmount during spinn

---

android/src/main/java/com/henninghall/date_picker/LocaleUtils.java
android/src/main/java/com/henninghall/date_picker/PickerView.java
android/src/main/java/com/henninghall/date_picker/Utils.java
android/src/main/java/com/henninghall/date_picker/ui/Accessibility.java
android/src/main/java/com/henninghall/date_picker/ui/UIManager.java
android/src/main/java/com/henninghall/date_picker/ui/WheelChangeListenerImpl.java
android/src/main/java/com/henninghall/date_picker/ui/Wheels.java
android/src/main/res/layout/ios_clone.xml
android/src/main/res/layout/native_picker.xml
android/src/main/res/values-fi/strings.xml
android/src/main/res/values-sv/strings.xml
android/src/main/res/values/strings.xml

The PR is aimed to provide accessibility support for the android picker. When the screen reader (**Android Phone Settings->Accessibility features->Accessibility->ScreenReader-> Toggle switch to on state**) for android devices is focussed on date picker the current version of date picker does not read any thing on the screen. This PR has now fixed this issue.
- When ScreenReader is now focussed on the Different Wheels, it will now read the content description for each wheel like select year, select day, select month, etc
- When user scrolls and selects any date, it will now read the content description as "**Selected {Wheel}, Value is 2nd December 2021 Time is 09 Hour: 30 Minutes**"
- Provided Localised support for above strings that will be read by the screen reader when the locale prop …

Feature - Add accessibility support for android date picker

---

android/src/main/res/values-nb/strings.xml
android/src/main/res/values-nn/strings.xml
android/src/main/res/values-no/strings.xml

Localized strings for Android for the Norwegian written languages bokmål (no, nb) and nynorsk (nn).
Tested on device by installing from our own git branch.

Translate a11y strings to Norwegian

---

android/src/main/res/values-he/strings.xml
android/src/main/res/values/strings.xml

fixes https://github.com/henninghall/react-native-date-picker/issues/342

fix: remove app_name string

---

android/src/main/java/com/henninghall/date_picker/pickers/IosClone.java
android/src/main/java/com/henninghall/date_picker/ui/Accessibility.java

My best effort on fixing #336 
- Does it by disabling onTouchEvent for all wheels but the one having accessibility focus (IosClone)
- Shouldn't affect anything when TalkBack isn't active
**BEFORE FIX**
**AFTER FIX**

Fix: Two-finger scroll issue when TalkBack is active

---

android/src/main/java/com/henninghall/date_picker/pickers/IosClone.java
android/src/main/java/com/henninghall/date_picker/ui/Accessibility.java

- Accessibility for IosPicker:
- Read changed display value out loud when scrolling and spoken feed back is enabled 
- TalkBack can detect standard date formats and parse them into very nice spoken version. So just reading display value should  be enough
**Changes**
- IosPicker: 
- OnValueChangeListenerInScrolling is stored in a variable, so we can add default functionality regardless of the listener 
- Accessibility:
- Added static functions for announcing things via spoken feedback / TalkBack

fix: talkback read display value on scroll value change

---

android/src/main/java/com/henninghall/date_picker/pickers/AndroidNative.java

probably fixes https://github.com/henninghall/react-native-date-picker/issues/368

fix: setTextColor should always run on superclass

---

android/src/main/java/com/henninghall/date_picker/LocaleUtils.java
android/src/main/java/com/henninghall/date_picker/PickerView.java
android/src/main/java/com/henninghall/date_picker/pickers/IosClone.java
android/src/main/java/com/henninghall/date_picker/pickers/Picker.java
android/src/main/java/com/henninghall/date_picker/ui/Accessibility.java
android/src/main/java/com/henninghall/date_picker/ui/UIManager.java
android/src/main/java/com/henninghall/date_picker/ui/WheelChangeListenerImpl.java
android/src/main/java/com/henninghall/date_picker/ui/Wheels.java
android/src/main/res/values-fi/strings.xml
android/src/main/res/values-he/strings.xml
android/src/main/res/values-nb/strings.xml
android/src/main/res/values-nn/strings.xml
android/src/main/res/values-no/strings.xml
android/src/main/res/values-sv/strings.xml
android/src/main/res/values/strings.xml

- Improve `IosClone` spoken feedback when wheel: 
- receives accessibility focus
- "12th of May, set date, slider, use volume keys to adjust"
- You can then use volume keys or 2-finger scroll to adjust value 
- when value changes
- Notify TalkBack about changes through accessibility events instead of explicitly announcing
- When used with physical keyboard, functions like OS sliders (android.widget.seekBar). For example brightness slider in notification shade. 
- Use accessibility initialisation listener to set contentDescription and other traits
- Moved accessibility logic only affecting IosClone from wheels to IosClone
- Refactor Accessibility class to be more tools, less use-case specific methods
Video has sound
https://user-images.githubusercontent.com/3703618/133783230-2eaa248d-61d6-4 …

feat: improved spoken feedback

---

android/src/main/res/layout/ios_clone.xml

The PR to resolve https://github.com/henninghall/react-native-date-picker/issues/372#issuecomment-979941197

fix: fixed is clone overlay focusable by talkback

---

ios/RNDatePicker/RNDatePickerManager.m

Fixes https://github.com/henninghall/react-native-date-picker/issues/398

fix: show picker modal from within another modal

---

android/src/main/java/com/henninghall/date_picker/HourDisplayBugWorkaround.java
android/src/main/java/com/henninghall/date_picker/wheels/HourWheel.java

Workaround for https://github.com/henninghall/react-native-date-picker/issues/382

fix: duplicate 12's renderd in android native variant

---

README.md
index.d.ts
ios/RNDatePicker/RNDatePickerManager.m
src/DatePickerIOS.js
src/propChecker.js
src/propTypes.js

Currently the iOS modal always presents in the system color theme (light or dark). Unfortunately our app is currently light mode only, and so makes assumptions about the colors which do not hold up when the modal is displayed in dark mode.
This PR adds the option `themeOverride`, which can be used to force the color theme of the iOS modal to either light or dark. If left off the color defaults to the system color, which is the current behavior.
This PR is additive only, there are no breaking changes.

Allow overriding the iOS modal theme (light/dark)

---

src/propTypes.js

In favor of https://github.com/henninghall/react-native-date-picker/pull/488/files

chore: remove usages of deprecated ViewPropTypes

---

ios/RNDatePicker/DatePicker.m

fixes https://github.com/henninghall/react-native-date-picker/issues/506 and https://github.com/henninghall/react-native-date-picker/issues/474

add import to fix builds failing on iOS

---

src/index.js

Fixes https://github.com/henninghall/react-native-date-picker/issues/527, https://github.com/henninghall/react-native-date-picker/issues/483

Support dark theme by default

---

README.md

The Expo guide on development builds and "Adding custom native code" should be sufficient to help developers to understand how to use this excellent library, with the added benefit of less space in your README taken up by these instructions :) This is the standard message we're advocating for in READMEs, documented here: https://expo.notion.site/Documenting-Expo-support-in-READMEs-f250a20b4bd5472cab0757918cb21062

Update Expo instructions in README to standard template

---

README.md

Just a small typo I noticed yesterday while reading the Documentation

fix: typo in the Readme

---

ios/RNDatePicker/RNDatePickerManager.m
src/DatePickerAndroid.js
src/DatePickerIOS.js
src/modal.js

Fixes https://github.com/henninghall/react-native-date-picker/issues/609

fix: prevent closing parent modal on picker modal close

---

.maestro/display-text.yml
.maestro/utils/swipe-wheel-1.yml
android/src/main/java/com/henninghall/date_picker/props/Prop.java
android/src/main/java/com/henninghall/date_picker/wheels/DayWheel.java

Wrong date was initially selected on android if date was in past and no max or min date was set. 
Fixes https://github.com/henninghall/react-native-date-picker/issues/633

fix: incorrect initial date when date in past

---

android/src/oldarch/java/com/henninghall/date_picker/DatePickerModule.java

Fixes https://github.com/henninghall/react-native-date-picker/issues/751

fix: Undefined is not a function / NativeModule.closePicker() error using old architecture

---

react-native-date-picker.podspec

without pinning the tag, the latest native files will be fetched by CocoaPods

fix: pin native ios code to tag version

---

android/src/oldarch/java/com/henninghall/date_picker/DatePickerManager.java

fixes https://github.com/henninghall/react-native-date-picker/issues/787

fix: divider color not working on old architecture

---

android/src/main/java/com/henninghall/date_picker/DatePickerModuleImpl.java
src/index.js

- Adaptable modal title color. Defaults to text color. Fixes https://github.com/henninghall/react-native-date-picker/issues/829
- Divider color uses text color by default (adapting to theme)
- Text color defaults to white at dark theme. Fixes https://github.com/henninghall/react-native-date-picker/issues/720

fix: improved theming and colors

---

android/src/main/java/com/henninghall/date_picker/DatePickerModuleImpl.java

"Fix resolveAttribute issue in DatePickerModuleImpl.java
Updated the line resolving the 'dialogPreferredPadding' attribute to include the 'android' prefix. This change corrects an error where the attribute could not be found, causing the build to fail on Android. 
Previous:
theme.resolveAttribute(R.attr.dialogPreferredPadding, typedValue, true);
Updated:
theme.resolveAttribute(android.R.attr.dialogPreferredPadding, typedValue, true);
This fix ensures that the correct system attribute is referenced, preventing the build failure."

fix: Resolve Attribute issue causing Android Build to fail

---

src/index.js

Currently when passing a theme of 'dark', the title changes to white, but the buttons do not. Also, buttonColor requires a hex value to be passed and not for example the hsl format. This PR changes buttonColor to have the same niceties as e.g. dividerColor, allowing various color formats and changing to white by default when the theme is dark.

Fix default button color on Android when in dark mode, allow buttonColor to take non-hex values

---

ios/RNDatePickerManager.mm

Fix crash introduced for old arch on iOS in `5.0.10`
```
[Exception thrown while executing UI block:-[_ _NSCFString timeIntervalSinceReferenceDate ]: unrecognized selector sent to instance
```
Fixes https://github.com/henninghall/react-native-date-picker/issues/896

fix: iOS old architecture crash 

---

ios/RNDatePickerManager.mm

Fixes https://github.com/henninghall/react-native-date-picker/issues/907
`no visible @interface for 'RNDatePicker'`

fix ios old architecture expo eas error

---

android/build.gradle

Adds a version check to conditionally set the namespace for Android builds using Gradle Plugin version 7.3.0 and above.

feat: Add Android Gradle Plugin namespace support

---

package.json

Fix deprecation warning by adding missing `ios.componentProvider` and `modulesProvider` [configuration](https://reactnative.dev/docs/the-new-architecture/using-codegen#configuring-codegen).
When using `react-native-date-picker`, the following deprecation warning appears:
```
[DEPRECATED] react-native-date-picker should add the 'ios.componentProvider' property in their codegenConfig
```
- Added the missing iOS configuration to the `codegenConfig` in `package.json`:
- componentProvider: Maps JavaScript RNDatePicker component to iOS RNDatePicker class
- modulesProvider: Maps JavaScript RNDatePicker module to iOS RNDatePickerManager class
- environment: expo sdk 53 & react-native v0.79.2
- Verified deprecation warning no longer appears
- UI component continues to work as expected
- Module …

fix: add ios.componentProvider and modulesProvider to codegenConfig
